/*
    THIS FILE CHECKS FOR ERRORS COULD HAPPEN.
    THEN ALERTING THE ERRORS BEFORE STARTING / DEBUGGING THE PROGRAM.

    Version : 0.0;
*/
const Build_Version='24/10/28';//YY/MM/DD.


//POINT TO START :
